export const HEROE_ADD = 'HEROE_ADD'
export const HEROE_REMOVE = 'HEROE_REMOVE'

export const HEROE_PEDIDO = 'HEROE_PEDIDO'
export const HEROE_EXITO = 'HEROE_EXITO'
export const HEROE_FRACASO = 'HEROE_FRACASO'

export const HEROE_PEDIDO_ID = 'HEROE_PEDIDO_ID'
export const HEROE_EXITO_ID = 'HEROE_EXITO_ID'
export const HEROE_FRACASO_ID = 'HEROE_FRACASO_ID'


